if (!this.enqueueMark) quit(0);
gczeal(0);
gcparam("incrementalWeakMapMarkingEnabled", 0);
gc(); gc();
var g_unc = newGlobal({newCompartment: true});
g_unc.eval(`grayRoot().h = Symbol("k");`);
var sym = g_unc.eval(`grayRoot().h`);
var g1 = newGlobal({newCompartment: true});
g1.s = sym;
sym = null;
g1.eval(`var wm = new WeakMap(); wm.set(s, {x:1}); s = null;`);
gc();
enqueueMark('enter-weak-marking-mode');
enqueueMark('abort-weak-marking-mode');
schedulezone(g1);
schedulezone(this);
schedulezone(Object.keys({a:1})[0]);
startgc(1);
finishgc();
